---
- name: Install AD features 
  ansible.windows.win_feature:
    name: 
     - AD-Domain-Services
     - DHCP
    include_management_tools: true
    include_sub_features: true
    state: present
  register: win_feature_result

- name: debug
  debug:
    var: win_feature_result


- name: Setting up DHCP server
  win_dhcp_scope:
     name: " DHCP"
     start_ip_address: "192.168.1.100"
     end_ip_address: "192.168.1.200"
     subnet_mask: "255.255.255.0"
     state: present

- name: Create a new forest
  ansible.windows.win_domain:
    dns_domain_name: happy.domain  # my fake happy.domain
    safe_mode_password: 'SuP3RstR0ngP4zzW0rdTAj' # notsecret
  register: win_domain_result

- name: debug
  debug:
    var: win_domain_result

- name: Reboot after creation
  ansible.windows.win_reboot:
  when: win_domain_result.reboot_required
