---
- name: Ping over windows
  hosts: windows
  vars:
    ansible_user: Administrator
    ansible_password: SuP3RstR0ngP4zzW0rd!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - ping:
